services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: php:8.2-fpm
        container_name: ticket_manager_app
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - ticket-manager
        depends_on:
            - db

    webserver:
        image: nginx:alpine
        container_name: ticket_manager_laravel_webserver
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - ticket-manager
        depends_on:
            - app

    db:
        image: mariadb:10.5
        container_name: ticker_manager_db
        environment:
            MYSQL_DATABASE: ticket-manager
            MYSQL_USER: ticket-manager
            MYSQL_PASSWORD: admin123
            MYSQL_ROOT_PASSWORD: admin123
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - ticket-manager

networks:
    ticket-manager:
        driver: bridge

volumes:
    dbdata:
        driver: local
