flowchart TD
    A[User] -->|Klickt + Knopf| B[Besuch hinzufügen Seite öffnen]
    B --> C[Input: Filmtitel]
    C -->|Autocomplete| D{Film in DB?}
    D -->|Ja| E[Film aus DB laden]
    D -->|Nein| F[Film in TMDb API suchen]
    
    E --> G[Plattform='local' und Film-ID zwischenspeichern]
    F --> H[Plattform='tmdb' und Film-ID zwischenspeichern]
    
    G --> I{Bild URL in DB?}
    H --> I
    
    I -->|Ja| J[Bild URL aus DB laden]
    I -->|Nein| K[Bild URL in TMDb API suchen]
    
    K --> L[Bild URL in DB speichern]
    J --> M[Besuch hinzufügen abschließen]
    L --> M
    
    style A fill:#f9f,stroke:#333,stroke-width:2px
    style M fill:#bbf,stroke:#333,stroke-width:2px